-- AlterTable
ALTER TABLE "Mapper" ADD COLUMN     "created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- CreateTable
CREATE TABLE "TransformData" (
    "id" SERIAL NOT NULL,
    "importId" INTEGER NOT NULL,
    "row" JSONB NOT NULL,
    "created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TransformData_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "TransformData" ADD CONSTRAINT "TransformData_importId_fkey" FOREIGN KEY ("importId") REFERENCES "Import"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
