# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tin Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "prototype" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
    - run: bun install
    - name: Start bun server
      run: nohup bun run dev &
    - name: Wait for server to start
      run: curl --head -X GET --retry 5 --retry-connrefused --retry-delay 5 http://localhost:3000 || exit 1
    - name: Run Test
      run: bun run test
